name: Release components package
on:
  release:
    types: [published]
  workflow_dispatch:
concurrency:
  group: "publish-npm"
  cancel-in-progress: true
jobs:
  build:
    environment: deploy_npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: pnpm install
      - name: Publish 🚀
        shell: bash
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
